### ISSUE TITLE
Lab exercise 4A

### ISSUE THREAD

**Issue by an3523** [OOP-NYUAD/Issues#2]
the question in exercise 4A states to "Write an inline function Min(int,int) to calculate minimum between 
two numbers", is printing which the smallest input enough? or are we suppose to calculate the difference between the two integers?

**Comment by Salous-99** [comment]
Sorry for the late reply, it's supposed to just return the minimum so Min(2, 5) should return 2.

I have enabled email notifications so I am able to reply faster in the future.
