### ISSUE TITLE
Task 7 input csv file

### ISSUE THREAD

**Issue by Salous-99** [OOP-NYUAD/Issues#3]
a question I was asked by a student: 

"Since we are not given the number of data, can we assume the number of data columns and rows and the content of the file and write the code according to what we know is in the file, such as that the file has the first column containing name of city (a string) and the second column contains the minimum temperature (a float), etc. and also assume the number of data entries (4). Or are we supposed to scan the file first and gain the relevant information about the file and code accordingly?"

**Comment by Salous-99** [comment]
As for the second part, I can confidently say that you cannot make any assumptions on how long the file is. It can have 4 entries or 40. How you approach the solution is up to you. I will highlight that you should all be comfortable with dynamic memory allocation and, as of our last lab, vectors.

As for the first part, I would say that it is reasonable to assume that you know the format and meaning of your input data. Which means you can assume that the city name is a string, the min and max as floats and the Area Code as a string (a string would be my go-to data type to store any identifier). However, I will leave this issue open until Prof. Alhanai affirms or rejects my answer.

**Comment by talhanai** [comment]
> "Since we are not given the number of data, can we assume the number of data columns and rows and the content of the file and write the code according to what we know is in the file, such as that the file has the first column containing name of city (a string) and the second column contains the minimum temperature (a float), etc. and also assume the number of data entries (4). Or are we supposed to scan the file first and gain the relevant information about the file and code accordingly?"

For simplicity, you can assume you know the size in advance, as well as the data types. This is not the most generalizable solution as Salous-99 has mentioned.

I hope this clarifies it.
